// ReSharper disable InconsistentNaming
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo
using static HSReflection.Reflection;

namespace HSReflection.Util;

public static class Services
{
    public static MonoWrapper IErrorService => new MonoWrapper(GetService("IErrorService"));
    public static MonoWrapper GameDownloadManager => new MonoWrapper(GetService("Hearthstone.Streaming.GameDownloadManager"));
    public static MonoWrapper Network => new MonoWrapper(GetService("Network"));
    public static MonoWrapper DownloadableDbfCache => new MonoWrapper(GetService("DownloadableDbfCache"));
    public static MonoWrapper EventTimingManager => new MonoWrapper(GetService("EventTimingManager"));
    public static MonoWrapper GameMgr => new MonoWrapper(GetService("GameMgr"));
    public static MonoWrapper DraftManager => new MonoWrapper(GetService("DraftManager"));
    public static MonoWrapper AdventureProgressMgr => new MonoWrapper(GetService("AdventureProgressMgr"));
    public static MonoWrapper AchieveManager => new MonoWrapper(GetService("AchieveManager"));
    public static MonoWrapper AchievementManager => new MonoWrapper(GetService("Hearthstone.Progression.AchievementManager"));
    public static MonoWrapper QuestManager => new MonoWrapper(GetService("Hearthstone.Progression.QuestManager"));
    public static MonoWrapper RewardTrackManager => new MonoWrapper(GetService("Hearthstone.Progression.RewardTrackManager"));
    public static MonoWrapper SpecialEventManager => new MonoWrapper(GetService("Hearthstone.Progression.SpecialEventManager"));
    public static MonoWrapper GenericRewardChestNoticeManager => new MonoWrapper(GetService("GenericRewardChestNoticeManager"));
    public static MonoWrapper AccountLicenseMgr => new MonoWrapper(GetService("AccountLicenseMgr"));
    public static MonoWrapper FixedRewardsMgr => new MonoWrapper(GetService("FixedRewardsMgr"));
    public static MonoWrapper ReturningPlayerMgr => new MonoWrapper(GetService("ReturningPlayerMgr"));
    public static MonoWrapper FreeDeckMgr => new MonoWrapper(GetService("FreeDeckMgr"));
    public static MonoWrapper DemoMgr => new MonoWrapper(GetService("DemoMgr"));
    public static MonoWrapper NetCache => new MonoWrapper(GetService("NetCache"));
    public static MonoWrapper GameDbf => new MonoWrapper(GetService("GameDbf"));
    public static MonoWrapper DebugConsole => new MonoWrapper(GetService("DebugConsole"));
    public static MonoWrapper TavernBrawlManager => new MonoWrapper(GetService("TavernBrawlManager"));
    public static MonoWrapper IAssetLoader => new MonoWrapper(GetService("IAssetLoader"));
    public static MonoWrapper IAliasedAssetResolver => new MonoWrapper(GetService("IAliasedAssetResolver"));
    public static MonoWrapper LoginManager => new MonoWrapper(GetService("LoginManager"));
    public static MonoWrapper CardBackManager => new MonoWrapper(GetService("CardBackManager"));
    public static MonoWrapper CheatMgr => new MonoWrapper(GetService("CheatMgr"));
    public static MonoWrapper Cheats => new MonoWrapper(GetService("Cheats"));
    public static MonoWrapper ReconnectMgr => new MonoWrapper(GetService("ReconnectMgr"));
    public static MonoWrapper DisconnectMgr => new MonoWrapper(GetService("DisconnectMgr"));
    public static MonoWrapper HealthyGamingMgr => new MonoWrapper(GetService("HealthyGamingMgr"));
    public static MonoWrapper SoundManager => new MonoWrapper(GetService("SoundManager"));
    public static MonoWrapper MusicManager => new MonoWrapper(GetService("MusicManager"));
    public static MonoWrapper RAFManager => new MonoWrapper(GetService("RAFManager"));
    public static MonoWrapper InactivePlayerKicker => new MonoWrapper(GetService("InactivePlayerKicker"));
    public static MonoWrapper ClientLocationManager => new MonoWrapper(GetService("ClientLocationManager"));
    public static MonoWrapper AdTrackingManager => new MonoWrapper(GetService("AdTrackingManager"));
    public static MonoWrapper SpellManager => new MonoWrapper(GetService("SpellManager"));
    public static MonoWrapper LocationServices => new MonoWrapper(GetService("LocationServices"));
    public static MonoWrapper WifiInfo => new MonoWrapper(GetService("WifiInfo"));
    public static MonoWrapper FiresideGatheringManager => new MonoWrapper(GetService("FiresideGatheringManager"));
    public static MonoWrapper GameplayErrorManager => new MonoWrapper(GetService("GameplayErrorManager"));
    public static MonoWrapper IFontTable => new MonoWrapper(GetService("Blizzard.T5.Fonts.IFontTable"));
    public static MonoWrapper UniversalInputManager => new MonoWrapper(GetService("UniversalInputManager"));
    public static MonoWrapper ScreenEffectsMgr => new MonoWrapper(GetService("ScreenEffectsMgr"));
    public static MonoWrapper ShownUIMgr => new MonoWrapper(GetService("ShownUIMgr"));
    public static MonoWrapper PerformanceAnalytics => new MonoWrapper(GetService("PerformanceAnalytics"));
    public static MonoWrapper PopupDisplayManager => new MonoWrapper(GetService("PopupDisplayManager"));
    public static MonoWrapper IGraphicsManager => new MonoWrapper(GetService("IGraphicsManager"));
    public static MonoWrapper MobilePermissionsManager => new MonoWrapper(GetService("MobilePermissionsManager"));
    public static MonoWrapper ShaderTime => new MonoWrapper(GetService("ShaderTime"));
    public static MonoWrapper MobileCallbackManager => new MonoWrapper(GetService("MobileCallbackManager"));
    public static MonoWrapper FullScreenFXMgr => new MonoWrapper(GetService("FullScreenFXMgr"));
    public static MonoWrapper SceneMgr => new MonoWrapper(GetService("SceneMgr"));
    public static MonoWrapper SetRotationManager => new MonoWrapper(GetService("SetRotationManager"));
    public static MonoWrapper Cinematic => new MonoWrapper(GetService("Cinematic"));
    public static MonoWrapper WidgetRunner => new MonoWrapper(GetService("Hearthstone.UI.WidgetRunner"));
    public static MonoWrapper SpriteAtlasProvider => new MonoWrapper(GetService("Hearthstone.UI.SpriteAtlasProvider"));
    public static MonoWrapper IProductDataService => new MonoWrapper(GetService("Hearthstone.Store.IProductDataService"));
    public static MonoWrapper HearthstoneCheckout => new MonoWrapper(GetService("HearthstoneCheckout"));
    public static MonoWrapper NetworkReachabilityManager => new MonoWrapper(GetService("NetworkReachabilityManager"));
    public static MonoWrapper VersionConfigurationService => new MonoWrapper(GetService("Hearthstone.Core.Streaming.VersionConfigurationService"));
    [Obsolete] public static MonoWrapper DeeplinkService => throw new NotSupportedException("Hearthstone.Core.Deeplinking.DeeplinkService");
    public static MonoWrapper ILoginService => new MonoWrapper(GetService("Hearthstone.Login.ILoginService"));
    public static MonoWrapper PartyManager => new MonoWrapper(GetService("PartyManager"));
    public static MonoWrapper PlayerMigrationManager => new MonoWrapper(GetService("PlayerMigrationManager"));
    public static MonoWrapper CoinManager => new MonoWrapper(GetService("CoinManager"));
    public static MonoWrapper QuestToastManager => new MonoWrapper(GetService("Hearthstone.Progression.QuestToastManager"));
    public static MonoWrapper RewardXpNotificationManager => new MonoWrapper(GetService("Hearthstone.Progression.RewardXpNotificationManager"));
    public static MonoWrapper IMaterialService => new MonoWrapper(GetService("Blizzard.T5.MaterialService.IMaterialService"));
    public static MonoWrapper InGameMessageScheduler => new MonoWrapper(GetService("Hearthstone.InGameMessage.InGameMessageScheduler"));
    public static MonoWrapper DisposablesCleaner => new MonoWrapper(GetService("Blizzard.T5.AssetManager.DisposablesCleaner"));
    public static MonoWrapper PrefabInstanceLoadTracker => new MonoWrapper(GetService("PrefabInstanceLoadTracker"));
    public static MonoWrapper ExternalUrlService => new MonoWrapper(GetService("ExternalUrlService"));
    public static MonoWrapper DiamondRenderToTextureService => new MonoWrapper(GetService("DiamondRenderToTextureService"));
    public static MonoWrapper MessagePopupDisplay => new MonoWrapper(GetService("Hearthstone.InGameMessage.UI.MessagePopupDisplay"));
    public static MonoWrapper PrivacyGate => new MonoWrapper(GetService("PrivacyGate"));
    public static MonoWrapper APIGatewayService => new MonoWrapper(GetService("Hearthstone.APIGateway.APIGatewayService"));
    public static MonoWrapper BreakingNews => new MonoWrapper(GetService("Hearthstone.BreakingNews.BreakingNews"));
    public static MonoWrapper IGameStringsService => new MonoWrapper(GetService("IGameStringsService"));
    public static MonoWrapper LuckyDrawManager => new MonoWrapper(GetService("LuckyDrawManager"));
    public static MonoWrapper CameraManager => new MonoWrapper(GetService("CameraManager"));
    public static MonoWrapper LegendaryHeroRenderToTextureService => new MonoWrapper(GetService("LegendaryHeroRenderToTextureService"));
    public static MonoWrapper ActorNames => new MonoWrapper(GetService("ActorNames"));
    public static MonoWrapper ITouchScreenService => new MonoWrapper(GetService("ITouchScreenService"));
}